### ISSUE TITLE
Верно ли то, что в конструкциях `switch` нет оператора `break`?

### ISSUE THREAD

**Issue by s-belichenko** [bibimij/sendsay#1]
Например, такой (или подобный) кусок кода встречается не раз:

```
        switch ($this->params['result']) {
            case 'email':
                $this->params['email'] = $result;
            case 'save':
                $this->params['result.format'] = $format;
        }
```
Ведь без `break` у нас в случае, если верно условие для первого `case`, безусловно выполнится код и из второго `case`.

@ishapkin, вас тоже на всякий привлеку :-)

**Comment by ishapkin** [comment]
Привет! Древнее зло пробудилось (это я про библиотеку).
Я думаю что верно, иначе result.format не поставится. Но решение так себе конечно.
Я ее дописывал исходя из принципов "работает не трогай" и "так исторически сложилось".

**Comment by s-belichenko** [comment]
Ну сам Sendsay-то вроде живет, я аж удивился что так мало заинтересованных в его API :-)

> Я думаю что верно, иначе result.format не поставится.

Там вообще крышеснос, полный код примерно такой в нескольких местах:

```
    $this->params = $this->auth + $filter + array(
                'action'   => 'stat.activity',
                'sort'     => 'date',
                'desc'     => 1,
                'result'   => is_array($result) ? 'email' : $result,
                'page'     => $page,
                'pagesize' => $limit
            );

         switch ($this->params['result']) {
             case 'email':
                 $this->params['email'] = $result;
                 $this->params['result.format'] = $format;
                 break;
             case 'save':
                 $this->params['result.format'] = $format;
                 break;
         }
```
Выходит, мы сначала проверяем, является ли у нас `$result` массивом, и если да, то полю `result` в массиве `params` присваиваем `email`. А потом в `switch` уже еще раз проверяем, что мы там присвоили тому полю, и если `email`, то в итоге переписываем это значение на массив, который у нас в `$result`, и заодно еще формат задаем, без проверки.

Но если у нас в `$result` не массив, то мы это значение присваиваем туда же, но потом вместо кручу-верчу с ним в `switch` просто проверяем, равна ли эта переменная `save`, и если да, то задаем формат. Вроде так?

В общем, я бы предложил банальное:

```
        switch ($this->params['result']) {
            case 'email':
                $this->params['email'] = $result;
                $this->params['result.format'] = $format;
                break;
            case 'save':
                $this->params['result.format'] = $format;
                break;
        }
```
Как по мне, так и читаемо, и верно - у нас же все равно `$format` всегда чему-то равен (он там в функциях имеет значение по умолчанию).

**Comment by ishapkin** [comment]
Ну ты вообще как-то просто все написал. Менеджеру не понравится.

**Comment by bibimij** [comment]
Честно, я уже не помню почему так. Sendsay хорош, но API у него было неконсистентное.
Про переход к следующему условию при отсутствии break я знал, конечно же. Так что это фича. :)

**Comment by ishapkin** [comment]
> но API у него было неконсистентное

Какое емкое название для плохой документации :)
